### Find All Content
GET http://localhost:8080/api/content

### Find Content by ID
GET http://localhost:8080/api/content


### Create new Content
POST http://localhost:8080/api/content
Content-Type: application/json
{
    "id": 2, 
    "title": "My Second Blog Post",
    "desc": "My Second blog post",
    "Status": "IDEA",
    "Type" :"ARTICLE",
    "dateCreated": "2023-02-13T10:25:02.838496",
    "dateUpdated": null,
    "url": ""
}

### Update exisiting Content
PUT http://localhost:8080/api/content/1
Content-Type: application/json
{
    "id": 1, 
    "title": "MY FIRST POST!!!",
    "desc": "MY FIRST POST!!!",
    "Status": "IDEA",
    "Type" :"ARTICLE",
    "dateCreated": "2023-02-13T10:25:02.838496",
    "dateUpdated": "2023-02-13T10:25:02.838496",
    "url": "http://localhost:8080/my-first-blog-post"
}